### ISSUE TITLE
'Deploy' Stage Failed - Delivery Pipeline - IBM Cloud Foundry App

### ISSUE THREAD

**Issue by SBTMentor** [IBM/watson-assistant-slots-intro#129]
[watson-conversation-slots-intro-20191002150823479-log.txt](https://github.com/IBM/watson-assistant-slots-intro/files/3681870/watson-conversation-slots-intro-20191002150823479-log.txt)

The deployment is failing in the delivery pipeline. Kindly guide me in resolving the issue.

Best,

**Comment by scottdangelo** [comment]
Can you please run `cf logs watson-conversation-slots-intro-20191002150823479 --recent` to see if there is more info there?
