### ISSUE TITLE
Can't find the Workspace ID

### ISSUE THREAD

**Issue by arbridev** [IBM/watson-assistant-slots-intro#147]
Using this instructions I can't find the workspace id, instead the info in View API Details is:
## Skill details

Skill name:WatsonPizzeria
Skill ID:...
Legacy v1 workspace URL:...

## Service credentials 

Service credentials name:Auto-generated service credentials
API key:...

**Comment by rhagarty** [comment]
@arbridev the Assistant tooling is going through changes and the instructions need updating.  For example, "Assistant ID" is the new key name.

Have you tried using the "Skill ID" in place of the "Workshop ID"?

**Comment by arbridev** [comment]
Thanks @rhagarty, that is the solution, to use the "Skill ID" as the "Workspace ID"
